apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: waits-dispatcher-nodejs
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
      - image: villardl/wait-dispatcher-nodejs
        volumeMounts:
        - name: waits-nodejs
          mountPath: /etc/config.json
          subPath: config.json
      volumes:
        - name: waits-nodejs
          configMap:
            name: waits-nodejs